; Sorting settings for the Pocket Dimension
[General]
fAlternateDeathExpLoss=0.1
fAlternateDeathGoldLoss=0.25
iSaltGeneratorAmount=20
iSellIntervalDays=7
fSellValuePct=0.25

[Sorting]
bSortArmor=1
bSortAmmo=1
bSortOre=1
bSortClutter=1
bSortBook=1
bSortFirewood=1
bSortFood=1
bSortGem=1
bSortGold=0
bSortIngredient=1
bSortLeather=1
bSortPotions=1
bSortPoisons=1
bSortSoulGems=1
bSortWeapons=1
bSortScrolls=1
bSortJewelry=1
bSortQuestItems=0